# Generated by Django 5.0.8 on 2024-10-07 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Response',
            new_name='Respuesta',
        ),
    ]
