# Generated by Django 5.0.8 on 2024-10-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0002_rename_response_respuesta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(to='sentirseBien.service'),
        ),
    ]
