# Generated by Django 5.0.8 on 2024-09-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0004_post_alias_alter_post_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='isEmployee',
            field=models.BooleanField(default=False),
        ),
    ]
