# Generated by Django 5.0.8 on 2024-10-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0004_payment_paymenttype_appointment_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_appointment', to='sentirseBien.appointment'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointment_payment', to='sentirseBien.payment'),
        ),
    ]
