# Generated by Django 5.0.8 on 2024-10-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0006_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cuit',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
