# Generated by Django 5.0.8 on 2024-10-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentirseBien', '0008_alter_payment_appointment_alter_payment_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
